import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header/component";
import Footer from "@/components/Footer/component";
import Link from "next/link";
import "./globals.css";
import "./layout.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = [
    { href: "/", label: "Home" },
    { href: "/feed", label: "Feed" },
    { href: "/auth", label: "Authentication" },
    { href: "/places", label: "Places" },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className={`layout-wrapper ${geistSans.variable} ${geistMono.variable} `}
        >
          <Header />
          <main className="">
            <div className="layout-link ">
              {links.map((link, index) => (
                <Link key={index} href={link.href}>
                  {link.label}
                </Link>
              ))}
            </div>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
