import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header/component";
import Footer from "@/components/Footer/component";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className={`${geistSans.variable} ${geistMono.variable} antialiased w-full min-h-screen flex flex-col justify-between items-center`}
        >
          <Header />
          <main className="flex flex-col gap-8 row-start-2 items-center justify-center sm:items-start">
            <div className="flex justify-center gap-4 mx-auto mt-10 w-full">
              <Link href={"/feed"}>Feed</Link>
              <Link href={"/auth"}>Authentication</Link>
            </div>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
